# Generated by Django 2.2.10 on 2021-10-20 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя группы')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Тип ответа')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(verbose_name='Вопрос')),
                ('tlist_json', models.TextField(verbose_name='Варианты ответа')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.Groups')),
                ('qtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.Types')),
            ],
        ),
        migrations.CreateModel(
            name='Quests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование анкеты')),
                ('user_noauth', models.IntegerField(verbose_name='Пользователь не авторизированны')),
                ('user_auth', models.IntegerField(verbose_name='Пользователь авторизированный')),
                ('time_begin', models.DateTimeField(auto_now_add=True, verbose_name='Начальная дата')),
                ('time_end', models.DateTimeField(auto_now=True, verbose_name='Коечная дата')),
                ('descriptin', models.CharField(max_length=150, verbose_name='Описание анкеты')),
                ('answer_json', models.TextField(verbose_name='Ответы')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Groups')),
            ],
        ),
    ]
