# Generated by Django 2.2.10 on 2021-10-20 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.IntegerField(verbose_name='Вопрос')),
                ('value', models.TextField(verbose_name='Ответ')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Quests')),
            ],
        ),
        migrations.CreateModel(
            name='TList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя группы')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.Tasks')),
            ],
        ),
    ]
