# Generated by Django 2.2.10 on 2021-10-20 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_tlist_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='qtype',
            new_name='ttype',
        ),
        migrations.RemoveField(
            model_name='quests',
            name='answer_json',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='tlist_json',
        ),
    ]
