# Generated by Django 2.2.10 on 2021-10-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20211020_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task',
            field=models.CharField(max_length=150, verbose_name='Вопрос'),
        ),
    ]
