# Generated by Django 2.2.10 on 2021-10-20 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20211020_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='task',
            new_name='name',
        ),
    ]
