# Generated by Django 2.2.10 on 2021-10-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20211020_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quests',
            name='descriptin',
            field=models.CharField(max_length=150, null=True, verbose_name='Описание анкеты'),
        ),
        migrations.AlterField(
            model_name='quests',
            name='user_auth',
            field=models.IntegerField(null=True, verbose_name='Пользователь авторизированный'),
        ),
        migrations.AlterField(
            model_name='work',
            name='value',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
    ]
