# Generated by Django 2.2.10 on 2021-10-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20211021_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quests',
            name='user_auth',
            field=models.CharField(max_length=200, null=True, verbose_name='Id пользователя'),
        ),
    ]
