# Generated by Django 2.2.10 on 2021-10-21 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20211021_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quests',
            name='time_begin',
        ),
        migrations.RemoveField(
            model_name='quests',
            name='time_end',
        ),
    ]
