# Generated by Django 2.2.10 on 2021-10-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20211021_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quests',
            old_name='descriptin',
            new_name='description',
        ),
    ]
