# Generated by Django 2.2.10 on 2021-10-21 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20211021_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='quests',
            name='time_begin',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Начальная дата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quests',
            name='time_end',
            field=models.DateTimeField(auto_now=True, verbose_name='Коечная дата'),
        ),
    ]
