# Generated by Django 2.2.10 on 2021-10-21 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20211021_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Tasks'),
        ),
    ]
