# Generated by Django 2.2.10 on 2021-10-21 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20211021_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_name', to='app1.Tasks'),
        ),
    ]
