# Generated by Django 2.2.10 on 2021-10-21 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20211021_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='app1.Groups'),
        ),
    ]
