# Generated by Django 2.2.10 on 2021-10-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20211021_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='task',
            field=models.IntegerField(),
        ),
    ]
